create user sandbox;
create database SANDBOXDEV;

create table USUARIO (
    USUA_ID INT PRIMARY KEY NOT NULL,
    USUA_NOME VARCHAR(128),
    USUA_LOGIN VARCHAR(64),
    USUA_SENHA VARCHAR(256),
    USUA_DT_CRIACAO DATE,
    USUA_STATUS VARCHAR(64),
    USUA_ROLE VARCHAR (64)
);

create table USUARIO_AUTENTICACAO (
    UAUT_ID INT PRIMARY KEY NOT NULL,
    UAUT_ID_USUA INT REFERENCES USUARIO(USUA_ID),
    UAUT_DT_AUTENTICACAO TIMESTAMP,
    UAUT_TOKEN VARCHAR(256)
);

